/* ============================================================
 CENTRALIZEDEHR - POSTGRESQL DATA WAREHOUSE / DATA MART SCRIPT
 Chuyển đổi từ bản SQL Server local sang PostgreSQL.

 Cách dùng khuyến nghị:
   1. Tạo database trước trong pgAdmin/DBeaver/psql:
        CREATE DATABASE centralizedehr_dwh;
   2. Kết nối vào database centralizedehr_dwh.
   3. Chạy toàn bộ script này.

 Ghi chú chuyển đổi chính:
   - SQL Server USE/GO/OBJECT_ID/IDENTITY_INSERT được thay bằng cú pháp PostgreSQL.
   - NVARCHAR -> VARCHAR/TEXT, UNIQUEIDENTIFIER -> UUID, DATETIME2 -> TIMESTAMP(0), BIT -> BOOLEAN.
   - BIGINT IDENTITY(1,1) -> BIGINT GENERATED BY DEFAULT AS IDENTITY.
   - Tên bảng/cột đổi sang snake_case để đúng phong cách PostgreSQL.
   - Phần ETL từ OLTP nên chạy sau khi đã có bảng nguồn; mặc định giả định OLTP nằm trong schema public.
============================================================ */

-- ============================================================
-- 0. EXTENSIONS
-- ============================================================

-- Dùng cho hàm digest() khi hash CCCD/BHYT trong ETL mẫu.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- 1. CREATE SCHEMAS
-- ============================================================

CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS dwh;
CREATE SCHEMA IF NOT EXISTS mart;

-- ============================================================
-- 2. DIMENSION TABLES
-- ============================================================

-- 2.1. DIM DATE
CREATE TABLE IF NOT EXISTS dwh.dim_date (
    date_key        INT PRIMARY KEY,      -- YYYYMMDD, 0 = UNKNOWN
    full_date       DATE NULL,
    day_of_month    SMALLINT NULL,
    month_number    SMALLINT NULL,
    month_name      VARCHAR(20) NULL,
    quarter_number  SMALLINT NULL,
    year_number     SMALLINT NULL,
    week_of_year    SMALLINT NULL,
    is_weekend      BOOLEAN NOT NULL DEFAULT FALSE
);

-- 2.2. DIM PATIENT
CREATE TABLE IF NOT EXISTS dwh.dim_patient (
    patient_key          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id_source    UUID NULL,
    identity_hash        VARCHAR(64) NULL,
    insurance_code_hash  VARCHAR(64) NULL,
    gender               VARCHAR(20) NULL,
    date_of_birth        DATE NULL,
    age_group            VARCHAR(50) NULL,
    created_date         DATE NULL,
    effective_from       TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    effective_to         TIMESTAMP(0) NULL,
    is_current           BOOLEAN NOT NULL DEFAULT TRUE,
    source_system        VARCHAR(100) NOT NULL DEFAULT 'CentralizedEHR',
    loaded_at            TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_patient_current
ON dwh.dim_patient(patient_id_source)
WHERE is_current = TRUE AND patient_id_source IS NOT NULL;

-- 2.3. DIM HOSPITAL
CREATE TABLE IF NOT EXISTS dwh.dim_hospital (
    hospital_key        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id_source  UUID NULL,
    hospital_code       VARCHAR(50) NULL,
    hospital_name       VARCHAR(255) NOT NULL,
    hospital_level      VARCHAR(50) NULL,
    address             VARCHAR(500) NULL,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_date        DATE NULL,
    loaded_at           TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_hospital_source
ON dwh.dim_hospital(hospital_id_source)
WHERE hospital_id_source IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_hospital_code
ON dwh.dim_hospital(hospital_code)
WHERE hospital_code IS NOT NULL;

-- 2.4. DIM DOCTOR
CREATE TABLE IF NOT EXISTS dwh.dim_doctor (
    doctor_key          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id_source    UUID NULL,
    practicing_license  VARCHAR(100) NULL,
    doctor_name         VARCHAR(255) NULL,
    specialty           VARCHAR(255) NULL,
    hospital_key        BIGINT NOT NULL DEFAULT 0,
    effective_from      TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    effective_to        TIMESTAMP(0) NULL,
    is_current          BOOLEAN NOT NULL DEFAULT TRUE,
    loaded_at           TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dim_doctor_dim_hospital
        FOREIGN KEY (hospital_key) REFERENCES dwh.dim_hospital(hospital_key)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_doctor_current
ON dwh.dim_doctor(doctor_id_source)
WHERE is_current = TRUE AND doctor_id_source IS NOT NULL;

-- 2.5. DIM DISEASE
CREATE TABLE IF NOT EXISTS dwh.dim_disease (
    disease_key    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icd10_code     VARCHAR(50) NOT NULL UNIQUE,
    disease_name   VARCHAR(255) NULL,
    disease_group  VARCHAR(255) NULL,
    description    TEXT NULL,
    loaded_at      TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2.6. DIM DRUG
CREATE TABLE IF NOT EXISTS dwh.dim_drug (
    drug_key     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_code    VARCHAR(100) NOT NULL UNIQUE,
    drug_name    VARCHAR(255) NULL,
    drug_group   VARCHAR(255) NULL,
    description  TEXT NULL,
    metadata     JSONB NULL,
    loaded_at    TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2.7. DIM SERVICE - mở rộng cho Finance Mart
CREATE TABLE IF NOT EXISTS dwh.dim_service (
    service_key   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_code  VARCHAR(100) NOT NULL UNIQUE,
    service_name  VARCHAR(255) NULL,
    service_type  VARCHAR(100) NULL,
    description   TEXT NULL,
    loaded_at     TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2.8. DIM INSURANCE - mở rộng cho Finance Mart
CREATE TABLE IF NOT EXISTS dwh.dim_insurance (
    insurance_key   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insurance_type  VARCHAR(100) NOT NULL UNIQUE,
    coverage_rate   NUMERIC(5,2) NULL,
    description     TEXT NULL,
    loaded_at       TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 3. UNKNOWN ROWS
-- Dùng key = 0 để xử lý trường hợp lookup không tìm thấy.
-- ============================================================

INSERT INTO dwh.dim_date (
    date_key, full_date, day_of_month, month_number, month_name,
    quarter_number, year_number, week_of_year, is_weekend
)
VALUES (0, NULL, NULL, NULL, 'UNKNOWN', NULL, NULL, NULL, FALSE)
ON CONFLICT (date_key) DO NOTHING;

INSERT INTO dwh.dim_hospital (
    hospital_key, hospital_id_source, hospital_code, hospital_name,
    hospital_level, address, is_active, loaded_at
)
VALUES (0, NULL, 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', NULL, FALSE, CURRENT_TIMESTAMP)
ON CONFLICT (hospital_key) DO NOTHING;

INSERT INTO dwh.dim_patient (
    patient_key, patient_id_source, gender, age_group,
    effective_from, is_current, source_system, loaded_at
)
VALUES (0, NULL, 'UNKNOWN', 'UNKNOWN', CURRENT_TIMESTAMP, TRUE, 'SYSTEM', CURRENT_TIMESTAMP)
ON CONFLICT (patient_key) DO NOTHING;

INSERT INTO dwh.dim_doctor (
    doctor_key, doctor_id_source, practicing_license, doctor_name,
    specialty, hospital_key, effective_from, is_current, loaded_at
)
VALUES (0, NULL, 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', 0, CURRENT_TIMESTAMP, TRUE, CURRENT_TIMESTAMP)
ON CONFLICT (doctor_key) DO NOTHING;

INSERT INTO dwh.dim_disease (
    disease_key, icd10_code, disease_name, disease_group, description, loaded_at
)
VALUES (0, 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', 'Unknown disease / missing ICD-10', CURRENT_TIMESTAMP)
ON CONFLICT (disease_key) DO NOTHING;

INSERT INTO dwh.dim_drug (
    drug_key, drug_code, drug_name, drug_group, description, loaded_at
)
VALUES (0, 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', 'Unknown drug / missing drug code', CURRENT_TIMESTAMP)
ON CONFLICT (drug_key) DO NOTHING;

INSERT INTO dwh.dim_service (
    service_key, service_code, service_name, service_type, description, loaded_at
)
VALUES (0, 'UNKNOWN', 'UNKNOWN', 'UNKNOWN', 'Unknown service', CURRENT_TIMESTAMP)
ON CONFLICT (service_key) DO NOTHING;

INSERT INTO dwh.dim_insurance (
    insurance_key, insurance_type, coverage_rate, description, loaded_at
)
VALUES (0, 'UNKNOWN', NULL, 'Unknown insurance', CURRENT_TIMESTAMP)
ON CONFLICT (insurance_key) DO NOTHING;

-- Đưa sequence sau unknown row về tối thiểu là 1 để các bản ghi mới không bị trùng key 0.
SELECT setval(pg_get_serial_sequence('dwh.dim_patient', 'patient_key'), GREATEST((SELECT MAX(patient_key) FROM dwh.dim_patient), 1), (SELECT MAX(patient_key) > 0 FROM dwh.dim_patient));
SELECT setval(pg_get_serial_sequence('dwh.dim_hospital', 'hospital_key'), GREATEST((SELECT MAX(hospital_key) FROM dwh.dim_hospital), 1), (SELECT MAX(hospital_key) > 0 FROM dwh.dim_hospital));
SELECT setval(pg_get_serial_sequence('dwh.dim_doctor', 'doctor_key'), GREATEST((SELECT MAX(doctor_key) FROM dwh.dim_doctor), 1), (SELECT MAX(doctor_key) > 0 FROM dwh.dim_doctor));
SELECT setval(pg_get_serial_sequence('dwh.dim_disease', 'disease_key'), GREATEST((SELECT MAX(disease_key) FROM dwh.dim_disease), 1), (SELECT MAX(disease_key) > 0 FROM dwh.dim_disease));
SELECT setval(pg_get_serial_sequence('dwh.dim_drug', 'drug_key'), GREATEST((SELECT MAX(drug_key) FROM dwh.dim_drug), 1), (SELECT MAX(drug_key) > 0 FROM dwh.dim_drug));
SELECT setval(pg_get_serial_sequence('dwh.dim_service', 'service_key'), GREATEST((SELECT MAX(service_key) FROM dwh.dim_service), 1), (SELECT MAX(service_key) > 0 FROM dwh.dim_service));
SELECT setval(pg_get_serial_sequence('dwh.dim_insurance', 'insurance_key'), GREATEST((SELECT MAX(insurance_key) FROM dwh.dim_insurance), 1), (SELECT MAX(insurance_key) > 0 FROM dwh.dim_insurance));

-- ============================================================
-- 4. FACT TABLES
-- ============================================================

-- 4.1. FACT ENCOUNTER
-- Grain: một lượt khám của một bệnh nhân tại một bệnh viện, do một bác sĩ phụ trách.
CREATE TABLE IF NOT EXISTS dwh.fact_encounter (
    encounter_key          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id_source    UUID NULL,
    visit_date_key         INT NOT NULL,
    patient_key            BIGINT NOT NULL,
    hospital_key           BIGINT NOT NULL,
    doctor_key             BIGINT NOT NULL,
    disease_key            BIGINT NOT NULL,
    encounter_count        INT NOT NULL DEFAULT 1,
    has_lab_result         BOOLEAN NOT NULL DEFAULT FALSE,
    has_imaging_report     BOOLEAN NOT NULL DEFAULT FALSE,
    has_prescription       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at_source      TIMESTAMP(0) NULL,
    loaded_at              TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    batch_id               VARCHAR(100) NULL,

    CONSTRAINT uq_fact_encounter_source UNIQUE (encounter_id_source),
    CONSTRAINT fk_fact_encounter_dim_date FOREIGN KEY (visit_date_key) REFERENCES dwh.dim_date(date_key),
    CONSTRAINT fk_fact_encounter_dim_patient FOREIGN KEY (patient_key) REFERENCES dwh.dim_patient(patient_key),
    CONSTRAINT fk_fact_encounter_dim_hospital FOREIGN KEY (hospital_key) REFERENCES dwh.dim_hospital(hospital_key),
    CONSTRAINT fk_fact_encounter_dim_doctor FOREIGN KEY (doctor_key) REFERENCES dwh.dim_doctor(doctor_key),
    CONSTRAINT fk_fact_encounter_dim_disease FOREIGN KEY (disease_key) REFERENCES dwh.dim_disease(disease_key)
);

-- 4.2. FACT LAB RESULT
-- Grain: một kết quả xét nghiệm thuộc một lượt khám.
CREATE TABLE IF NOT EXISTS dwh.fact_lab_result (
    lab_result_key       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_result_id_source UUID NULL,
    encounter_id_source  UUID NULL,
    test_date_key        INT NOT NULL,
    patient_key          BIGINT NOT NULL,
    hospital_key         BIGINT NOT NULL,
    doctor_key           BIGINT NOT NULL,
    test_code            VARCHAR(100) NULL,
    test_name            VARCHAR(255) NULL,
    result_value         VARCHAR(255) NULL,
    unit                 VARCHAR(100) NULL,
    is_abnormal          BOOLEAN NULL,
    lab_result_count     INT NOT NULL DEFAULT 1,
    loaded_at            TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    batch_id             VARCHAR(100) NULL,

    CONSTRAINT uq_fact_lab_result_source UNIQUE (lab_result_id_source),
    CONSTRAINT fk_fact_lab_result_dim_date FOREIGN KEY (test_date_key) REFERENCES dwh.dim_date(date_key),
    CONSTRAINT fk_fact_lab_result_dim_patient FOREIGN KEY (patient_key) REFERENCES dwh.dim_patient(patient_key),
    CONSTRAINT fk_fact_lab_result_dim_hospital FOREIGN KEY (hospital_key) REFERENCES dwh.dim_hospital(hospital_key),
    CONSTRAINT fk_fact_lab_result_dim_doctor FOREIGN KEY (doctor_key) REFERENCES dwh.dim_doctor(doctor_key)
);

-- 4.3. FACT IMAGING REPORT
-- Grain: một báo cáo chẩn đoán hình ảnh thuộc một lượt khám.
CREATE TABLE IF NOT EXISTS dwh.fact_imaging_report (
    imaging_report_key       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imaging_report_id_source UUID NULL,
    encounter_id_source      UUID NULL,
    study_date_key           INT NOT NULL,
    patient_key              BIGINT NOT NULL,
    hospital_key             BIGINT NOT NULL,
    doctor_key               BIGINT NOT NULL,
    modality                 VARCHAR(50) NULL,
    imaging_report_count     INT NOT NULL DEFAULT 1,
    has_pacs_link            BOOLEAN NOT NULL DEFAULT FALSE,
    loaded_at                TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    batch_id                 VARCHAR(100) NULL,

    CONSTRAINT uq_fact_imaging_report_source UNIQUE (imaging_report_id_source),
    CONSTRAINT fk_fact_imaging_report_dim_date FOREIGN KEY (study_date_key) REFERENCES dwh.dim_date(date_key),
    CONSTRAINT fk_fact_imaging_report_dim_patient FOREIGN KEY (patient_key) REFERENCES dwh.dim_patient(patient_key),
    CONSTRAINT fk_fact_imaging_report_dim_hospital FOREIGN KEY (hospital_key) REFERENCES dwh.dim_hospital(hospital_key),
    CONSTRAINT fk_fact_imaging_report_dim_doctor FOREIGN KEY (doctor_key) REFERENCES dwh.dim_doctor(doctor_key)
);

-- 4.4. FACT PRESCRIPTION
-- Grain: một dòng thuốc được kê trong một lượt khám.
CREATE TABLE IF NOT EXISTS dwh.fact_prescription (
    prescription_key        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id_source  UUID NULL,
    encounter_id_source     UUID NULL,
    prescription_date_key   INT NOT NULL,
    patient_key             BIGINT NOT NULL,
    hospital_key            BIGINT NOT NULL,
    doctor_key              BIGINT NOT NULL,
    drug_key                BIGINT NOT NULL,
    quantity                NUMERIC(18,2) NULL,
    duration_days           INT NULL,
    prescription_line_count INT NOT NULL DEFAULT 1,
    loaded_at               TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    batch_id                VARCHAR(100) NULL,

    CONSTRAINT uq_fact_prescription_source UNIQUE (prescription_id_source),
    CONSTRAINT ck_fact_prescription_quantity CHECK (quantity IS NULL OR quantity >= 0),
    CONSTRAINT ck_fact_prescription_duration CHECK (duration_days IS NULL OR duration_days > 0),
    CONSTRAINT fk_fact_prescription_dim_date FOREIGN KEY (prescription_date_key) REFERENCES dwh.dim_date(date_key),
    CONSTRAINT fk_fact_prescription_dim_patient FOREIGN KEY (patient_key) REFERENCES dwh.dim_patient(patient_key),
    CONSTRAINT fk_fact_prescription_dim_hospital FOREIGN KEY (hospital_key) REFERENCES dwh.dim_hospital(hospital_key),
    CONSTRAINT fk_fact_prescription_dim_doctor FOREIGN KEY (doctor_key) REFERENCES dwh.dim_doctor(doctor_key),
    CONSTRAINT fk_fact_prescription_dim_drug FOREIGN KEY (drug_key) REFERENCES dwh.dim_drug(drug_key)
);

-- 4.5. FACT APPOINTMENT
-- Grain: một lịch hẹn khám.
CREATE TABLE IF NOT EXISTS dwh.fact_appointment (
    appointment_key        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id_source  UUID NULL,
    appointment_date_key   INT NOT NULL,
    patient_key            BIGINT NOT NULL,
    hospital_key           BIGINT NOT NULL,
    doctor_key             BIGINT NOT NULL,
    appointment_status     VARCHAR(50) NULL,
    appointment_count      INT NOT NULL DEFAULT 1,
    loaded_at              TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    batch_id               VARCHAR(100) NULL,

    CONSTRAINT uq_fact_appointment_source UNIQUE (appointment_id_source),
    CONSTRAINT fk_fact_appointment_dim_date FOREIGN KEY (appointment_date_key) REFERENCES dwh.dim_date(date_key),
    CONSTRAINT fk_fact_appointment_dim_patient FOREIGN KEY (patient_key) REFERENCES dwh.dim_patient(patient_key),
    CONSTRAINT fk_fact_appointment_dim_hospital FOREIGN KEY (hospital_key) REFERENCES dwh.dim_hospital(hospital_key),
    CONSTRAINT fk_fact_appointment_dim_doctor FOREIGN KEY (doctor_key) REFERENCES dwh.dim_doctor(doctor_key)
);

-- 4.6. FACT CONSENT
-- Grain: một quyền truy cập hồ sơ được cấp.
CREATE TABLE IF NOT EXISTS dwh.fact_consent (
    consent_key          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consent_id_source    UUID NULL,
    start_date_key       INT NOT NULL,
    end_date_key         INT NOT NULL,
    patient_key          BIGINT NOT NULL,
    doctor_key           BIGINT NOT NULL,
    hospital_key         BIGINT NOT NULL,
    consent_status       VARCHAR(50) NULL,
    consent_count        INT NOT NULL DEFAULT 1,
    valid_duration_days  INT NULL,
    loaded_at            TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    batch_id             VARCHAR(100) NULL,

    CONSTRAINT uq_fact_consent_source UNIQUE (consent_id_source),
    CONSTRAINT fk_fact_consent_start_date FOREIGN KEY (start_date_key) REFERENCES dwh.dim_date(date_key),
    CONSTRAINT fk_fact_consent_end_date FOREIGN KEY (end_date_key) REFERENCES dwh.dim_date(date_key),
    CONSTRAINT fk_fact_consent_dim_patient FOREIGN KEY (patient_key) REFERENCES dwh.dim_patient(patient_key),
    CONSTRAINT fk_fact_consent_dim_doctor FOREIGN KEY (doctor_key) REFERENCES dwh.dim_doctor(doctor_key),
    CONSTRAINT fk_fact_consent_dim_hospital FOREIGN KEY (hospital_key) REFERENCES dwh.dim_hospital(hospital_key)
);

-- 4.7. FACT PATIENT MAPPING
-- Grain: một ánh xạ giữa local_patient_id tại HIS và patient_id trung tâm.
CREATE TABLE IF NOT EXISTS dwh.fact_patient_mapping (
    mapping_key      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_key      BIGINT NOT NULL,
    hospital_key     BIGINT NOT NULL,
    local_patient_id VARCHAR(100) NOT NULL,
    mapping_date_key INT NOT NULL,
    mapping_count    INT NOT NULL DEFAULT 1,
    source_system    VARCHAR(100) NOT NULL DEFAULT 'HIS',
    loaded_at        TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    batch_id         VARCHAR(100) NULL,

    CONSTRAINT uq_fact_patient_mapping_hospital_local UNIQUE (hospital_key, local_patient_id),
    CONSTRAINT fk_fact_patient_mapping_dim_patient FOREIGN KEY (patient_key) REFERENCES dwh.dim_patient(patient_key),
    CONSTRAINT fk_fact_patient_mapping_dim_hospital FOREIGN KEY (hospital_key) REFERENCES dwh.dim_hospital(hospital_key),
    CONSTRAINT fk_fact_patient_mapping_dim_date FOREIGN KEY (mapping_date_key) REFERENCES dwh.dim_date(date_key)
);

-- 4.8. FACT HIS SYNC QUALITY
-- Grain: một lượt đồng bộ dữ liệu HIS lên trung tâm.
CREATE TABLE IF NOT EXISTS dwh.fact_his_sync_quality (
    sync_key                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_id_source              VARCHAR(100) NULL,
    hospital_key                BIGINT NOT NULL,
    sync_date_key               INT NOT NULL,
    source_system               VARCHAR(100) NULL,
    synced_encounter_count      INT NOT NULL DEFAULT 0,
    new_patient_count           INT NOT NULL DEFAULT 0,
    missing_icd10_count         INT NOT NULL DEFAULT 0,
    missing_prescription_count  INT NOT NULL DEFAULT 0,
    missing_lab_result_count    INT NOT NULL DEFAULT 0,
    failed_record_count         INT NOT NULL DEFAULT 0,
    sync_latency_seconds        INT NULL,
    loaded_at                   TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    batch_id                    VARCHAR(100) NULL,

    CONSTRAINT uq_fact_his_sync_quality_source UNIQUE (sync_id_source),
    CONSTRAINT fk_fact_his_sync_quality_dim_hospital FOREIGN KEY (hospital_key) REFERENCES dwh.dim_hospital(hospital_key),
    CONSTRAINT fk_fact_his_sync_quality_dim_date FOREIGN KEY (sync_date_key) REFERENCES dwh.dim_date(date_key)
);

-- 4.9. FACT BILLING - mở rộng khi có module thanh toán.
CREATE TABLE IF NOT EXISTS dwh.fact_billing (
    billing_key               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    billing_id_source         UUID NULL,
    encounter_id_source       UUID NULL,
    billing_date_key          INT NOT NULL,
    patient_key               BIGINT NOT NULL,
    hospital_key              BIGINT NOT NULL,
    doctor_key                BIGINT NULL,
    service_key               BIGINT NOT NULL,
    insurance_key             BIGINT NOT NULL,
    total_amount              NUMERIC(18,2) NOT NULL DEFAULT 0,
    insurance_covered_amount  NUMERIC(18,2) NOT NULL DEFAULT 0,
    patient_paid_amount       NUMERIC(18,2) NOT NULL DEFAULT 0,
    billing_count             INT NOT NULL DEFAULT 1,
    payment_status            VARCHAR(50) NULL,
    loaded_at                 TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    batch_id                  VARCHAR(100) NULL,

    CONSTRAINT ck_fact_billing_total CHECK (total_amount >= 0),
    CONSTRAINT ck_fact_billing_paid CHECK (insurance_covered_amount + patient_paid_amount <= total_amount),
    CONSTRAINT fk_fact_billing_dim_date FOREIGN KEY (billing_date_key) REFERENCES dwh.dim_date(date_key),
    CONSTRAINT fk_fact_billing_dim_patient FOREIGN KEY (patient_key) REFERENCES dwh.dim_patient(patient_key),
    CONSTRAINT fk_fact_billing_dim_hospital FOREIGN KEY (hospital_key) REFERENCES dwh.dim_hospital(hospital_key),
    CONSTRAINT fk_fact_billing_dim_doctor FOREIGN KEY (doctor_key) REFERENCES dwh.dim_doctor(doctor_key),
    CONSTRAINT fk_fact_billing_dim_service FOREIGN KEY (service_key) REFERENCES dwh.dim_service(service_key),
    CONSTRAINT fk_fact_billing_dim_insurance FOREIGN KEY (insurance_key) REFERENCES dwh.dim_insurance(insurance_key)
);

-- ============================================================
-- 5. ETL ERROR TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS dwh.etl_error_record (
    error_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_system    VARCHAR(100) NULL,
    source_table     VARCHAR(100) NULL,
    source_record_id VARCHAR(100) NULL,
    error_type       VARCHAR(100) NULL,
    error_message    TEXT NULL,
    raw_payload      JSONB NULL,
    created_at       TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    batch_id         VARCHAR(100) NULL
);

-- ============================================================
-- 6. INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS ix_fact_encounter_date ON dwh.fact_encounter(visit_date_key);
CREATE INDEX IF NOT EXISTS ix_fact_encounter_patient ON dwh.fact_encounter(patient_key);
CREATE INDEX IF NOT EXISTS ix_fact_encounter_hospital ON dwh.fact_encounter(hospital_key);
CREATE INDEX IF NOT EXISTS ix_fact_encounter_disease ON dwh.fact_encounter(disease_key);

CREATE INDEX IF NOT EXISTS ix_fact_prescription_date ON dwh.fact_prescription(prescription_date_key);
CREATE INDEX IF NOT EXISTS ix_fact_prescription_drug ON dwh.fact_prescription(drug_key);

CREATE INDEX IF NOT EXISTS ix_fact_appointment_date ON dwh.fact_appointment(appointment_date_key);
CREATE INDEX IF NOT EXISTS ix_fact_consent_status ON dwh.fact_consent(consent_status);

CREATE INDEX IF NOT EXISTS ix_fact_lab_result_date ON dwh.fact_lab_result(test_date_key);
CREATE INDEX IF NOT EXISTS ix_fact_imaging_report_date ON dwh.fact_imaging_report(study_date_key);
CREATE INDEX IF NOT EXISTS ix_fact_patient_mapping_hospital ON dwh.fact_patient_mapping(hospital_key);
CREATE INDEX IF NOT EXISTS ix_fact_his_sync_quality_date ON dwh.fact_his_sync_quality(sync_date_key);

-- ============================================================
-- 7. LOAD DIM_DATE
-- ============================================================

INSERT INTO dwh.dim_date (
    date_key, full_date, day_of_month, month_number, month_name,
    quarter_number, year_number, week_of_year, is_weekend
)
SELECT
    TO_CHAR(d::DATE, 'YYYYMMDD')::INT AS date_key,
    d::DATE AS full_date,
    EXTRACT(DAY FROM d)::SMALLINT AS day_of_month,
    EXTRACT(MONTH FROM d)::SMALLINT AS month_number,
    TRIM(TO_CHAR(d, 'Month')) AS month_name,
    EXTRACT(QUARTER FROM d)::SMALLINT AS quarter_number,
    EXTRACT(YEAR FROM d)::SMALLINT AS year_number,
    EXTRACT(WEEK FROM d)::SMALLINT AS week_of_year,
    CASE WHEN EXTRACT(ISODOW FROM d) IN (6, 7) THEN TRUE ELSE FALSE END AS is_weekend
FROM generate_series('2020-01-01'::DATE, '2035-12-31'::DATE, INTERVAL '1 day') AS gs(d)
ON CONFLICT (date_key) DO NOTHING;

-- ============================================================
-- 8. MART VIEWS FOR POWER BI / DASHBOARD
-- ============================================================

-- 8.1. Tổng lượt khám theo tháng và bệnh viện
CREATE OR REPLACE VIEW mart.vw_encounter_by_month_hospital AS
SELECT
    dd.year_number,
    dd.month_number,
    dh.hospital_name,
    dh.hospital_level,
    SUM(fe.encounter_count) AS total_encounters,
    SUM(CASE WHEN fe.has_lab_result = TRUE THEN 1 ELSE 0 END) AS encounters_with_lab,
    SUM(CASE WHEN fe.has_imaging_report = TRUE THEN 1 ELSE 0 END) AS encounters_with_imaging,
    SUM(CASE WHEN fe.has_prescription = TRUE THEN 1 ELSE 0 END) AS encounters_with_prescription
FROM dwh.fact_encounter fe
JOIN dwh.dim_date dd ON dd.date_key = fe.visit_date_key
JOIN dwh.dim_hospital dh ON dh.hospital_key = fe.hospital_key
GROUP BY
    dd.year_number,
    dd.month_number,
    dh.hospital_name,
    dh.hospital_level;

-- 8.2. Top bệnh / ICD-10
CREATE OR REPLACE VIEW mart.vw_top_disease AS
SELECT
    dis.icd10_code,
    dis.disease_name,
    dis.disease_group,
    SUM(fe.encounter_count) AS total_encounters
FROM dwh.fact_encounter fe
JOIN dwh.dim_disease dis ON dis.disease_key = fe.disease_key
GROUP BY
    dis.icd10_code,
    dis.disease_name,
    dis.disease_group;

-- 8.3. Lượt khám theo bác sĩ / chuyên khoa
CREATE OR REPLACE VIEW mart.vw_encounter_by_doctor_specialty AS
SELECT
    doc.doctor_name,
    doc.specialty,
    dh.hospital_name,
    SUM(fe.encounter_count) AS total_encounters
FROM dwh.fact_encounter fe
JOIN dwh.dim_doctor doc ON doc.doctor_key = fe.doctor_key
JOIN dwh.dim_hospital dh ON dh.hospital_key = fe.hospital_key
GROUP BY
    doc.doctor_name,
    doc.specialty,
    dh.hospital_name;

-- 8.4. Kê đơn thuốc theo tháng và thuốc
CREATE OR REPLACE VIEW mart.vw_prescription_by_month_drug AS
SELECT
    dd.year_number,
    dd.month_number,
    drug.drug_code,
    drug.drug_name,
    drug.drug_group,
    COUNT(*) AS prescription_lines,
    SUM(COALESCE(fp.quantity, 0)) AS total_quantity,
    AVG(fp.duration_days::NUMERIC(18,2)) AS avg_duration_days
FROM dwh.fact_prescription fp
JOIN dwh.dim_date dd ON dd.date_key = fp.prescription_date_key
JOIN dwh.dim_drug drug ON drug.drug_key = fp.drug_key
GROUP BY
    dd.year_number,
    dd.month_number,
    drug.drug_code,
    drug.drug_name,
    drug.drug_group;

-- 8.5. Lịch hẹn theo trạng thái
CREATE OR REPLACE VIEW mart.vw_appointment_status AS
SELECT
    dd.year_number,
    dd.month_number,
    dh.hospital_name,
    fa.appointment_status,
    SUM(fa.appointment_count) AS total_appointments
FROM dwh.fact_appointment fa
JOIN dwh.dim_date dd ON dd.date_key = fa.appointment_date_key
JOIN dwh.dim_hospital dh ON dh.hospital_key = fa.hospital_key
GROUP BY
    dd.year_number,
    dd.month_number,
    dh.hospital_name,
    fa.appointment_status;

-- 8.6. Consent theo trạng thái
CREATE OR REPLACE VIEW mart.vw_consent_status AS
SELECT
    dh.hospital_name,
    fc.consent_status,
    COUNT(*) AS total_consents,
    AVG(fc.valid_duration_days::NUMERIC(18,2)) AS avg_valid_duration_days
FROM dwh.fact_consent fc
JOIN dwh.dim_hospital dh ON dh.hospital_key = fc.hospital_key
GROUP BY
    dh.hospital_name,
    fc.consent_status;

-- 8.7. Mapping bệnh nhân theo bệnh viện
CREATE OR REPLACE VIEW mart.vw_patient_mapping_by_hospital AS
SELECT
    dh.hospital_name,
    dh.hospital_level,
    COUNT(*) AS total_mappings,
    COUNT(DISTINCT fpm.patient_key) AS total_mapped_patients,
    COUNT(DISTINCT fpm.local_patient_id) AS total_local_patient_ids
FROM dwh.fact_patient_mapping fpm
JOIN dwh.dim_hospital dh ON dh.hospital_key = fpm.hospital_key
GROUP BY
    dh.hospital_name,
    dh.hospital_level;

-- 8.8. KPI tổng quan hệ thống
CREATE OR REPLACE VIEW mart.vw_system_kpi_overview AS
SELECT
    (SELECT COUNT(*) FROM dwh.dim_patient WHERE patient_key <> 0 AND is_current = TRUE) AS total_patients,
    (SELECT COUNT(*) FROM dwh.dim_hospital WHERE hospital_key <> 0 AND is_active = TRUE) AS total_hospitals,
    (SELECT COUNT(*) FROM dwh.dim_doctor WHERE doctor_key <> 0 AND is_current = TRUE) AS total_doctors,
    (SELECT COALESCE(SUM(encounter_count), 0) FROM dwh.fact_encounter) AS total_encounters,
    (SELECT COUNT(*) FROM dwh.fact_prescription) AS total_prescription_lines,
    (SELECT COUNT(*) FROM dwh.fact_lab_result) AS total_lab_results,
    (SELECT COUNT(*) FROM dwh.fact_imaging_report) AS total_imaging_reports,
    (SELECT COUNT(*) FROM dwh.fact_appointment) AS total_appointments,
    (SELECT COUNT(*) FROM dwh.fact_consent) AS total_consents,
    CURRENT_TIMESTAMP AS refreshed_at;

-- ============================================================
-- 9. ETL MẪU TỪ OLTP POSTGRESQL SANG DWH
-- ============================================================
-- Mặc định giả định OLTP nằm trong cùng database, schema public.
-- Nếu bạn để OLTP ở schema khác, ví dụ oltp, hãy thay public.<table> thành oltp.<table>.
--
-- Lưu ý: PostgreSQL không query chéo database trực tiếp như SQL Server.
-- Nếu OLTP và DWH nằm ở 2 database khác nhau, dùng postgres_fdw hoặc ETL tool.
--
-- Phần dưới được comment để script tạo DWH chạy an toàn ngay cả khi chưa có bảng OLTP.
-- Khi đã có OLTP, bạn có thể bỏ comment từng block và chạy theo thứ tự.

/*
-- 9.1. LOAD DIM HOSPITAL
INSERT INTO dwh.dim_hospital (
    hospital_id_source, hospital_code, hospital_name,
    hospital_level, address, is_active, created_date, loaded_at
)
SELECT
    h.id AS hospital_id_source,
    h.code AS hospital_code,
    h.name AS hospital_name,
    h.level AS hospital_level,
    h.address AS address,
    CASE WHEN h.deleted_at IS NULL THEN TRUE ELSE FALSE END AS is_active,
    h.created_at::DATE AS created_date,
    CURRENT_TIMESTAMP AS loaded_at
FROM public.hospitals h
ON CONFLICT (hospital_id_source) WHERE hospital_id_source IS NOT NULL
DO UPDATE SET
    hospital_code  = EXCLUDED.hospital_code,
    hospital_name  = EXCLUDED.hospital_name,
    hospital_level = EXCLUDED.hospital_level,
    address        = EXCLUDED.address,
    is_active      = EXCLUDED.is_active,
    loaded_at      = CURRENT_TIMESTAMP;

-- 9.2. LOAD DIM DISEASE FROM MASTER_DATA
INSERT INTO dwh.dim_disease (
    icd10_code, disease_name, disease_group, description, loaded_at
)
SELECT
    md.code AS icd10_code,
    md.name AS disease_name,
    'UNKNOWN' AS disease_group,
    md.description AS description,
    CURRENT_TIMESTAMP AS loaded_at
FROM public.master_data md
WHERE md.data_type = 'ICD10'
  AND md.deleted_at IS NULL
  AND md.code IS NOT NULL
ON CONFLICT (icd10_code)
DO UPDATE SET
    disease_name  = EXCLUDED.disease_name,
    disease_group = EXCLUDED.disease_group,
    description   = EXCLUDED.description,
    loaded_at     = CURRENT_TIMESTAMP;

-- 9.3. LOAD DIM DRUG FROM MASTER_DATA
INSERT INTO dwh.dim_drug (
    drug_code, drug_name, drug_group, description, metadata, loaded_at
)
SELECT
    md.code AS drug_code,
    md.name AS drug_name,
    'UNKNOWN' AS drug_group,
    md.description AS description,
    md.metadata::JSONB AS metadata,
    CURRENT_TIMESTAMP AS loaded_at
FROM public.master_data md
WHERE md.data_type = 'DRUG'
  AND md.deleted_at IS NULL
  AND md.code IS NOT NULL
ON CONFLICT (drug_code)
DO UPDATE SET
    drug_name   = EXCLUDED.drug_name,
    drug_group  = EXCLUDED.drug_group,
    description = EXCLUDED.description,
    metadata    = EXCLUDED.metadata,
    loaded_at   = CURRENT_TIMESTAMP;

-- 9.4. LOAD DIM PATIENT
INSERT INTO dwh.dim_patient (
    patient_id_source, identity_hash, insurance_code_hash,
    gender, date_of_birth, age_group, created_date,
    effective_from, effective_to, is_current, source_system, loaded_at
)
SELECT
    p.id AS patient_id_source,
    CASE
        WHEN p.identity_number IS NULL OR BTRIM(p.identity_number) = '' THEN NULL
        ELSE ENCODE(DIGEST(p.identity_number::TEXT, 'sha256'), 'hex')
    END AS identity_hash,
    CASE
        WHEN p.insurance_code IS NULL OR BTRIM(p.insurance_code) = '' THEN NULL
        ELSE ENCODE(DIGEST(p.insurance_code::TEXT, 'sha256'), 'hex')
    END AS insurance_code_hash,
    p.gender AS gender,
    p.dob AS date_of_birth,
    CASE
        WHEN p.dob IS NULL THEN 'UNKNOWN'
        WHEN DATE_PART('year', AGE(CURRENT_DATE, p.dob)) < 6 THEN '0-5'
        WHEN DATE_PART('year', AGE(CURRENT_DATE, p.dob)) < 18 THEN '6-17'
        WHEN DATE_PART('year', AGE(CURRENT_DATE, p.dob)) < 35 THEN '18-34'
        WHEN DATE_PART('year', AGE(CURRENT_DATE, p.dob)) < 60 THEN '35-59'
        ELSE '60+'
    END AS age_group,
    p.created_at::DATE AS created_date,
    CURRENT_TIMESTAMP AS effective_from,
    NULL AS effective_to,
    TRUE AS is_current,
    'CentralizedEHR' AS source_system,
    CURRENT_TIMESTAMP AS loaded_at
FROM public.patients p
WHERE p.deleted_at IS NULL
ON CONFLICT (patient_id_source) WHERE is_current = TRUE AND patient_id_source IS NOT NULL
DO UPDATE SET
    identity_hash        = EXCLUDED.identity_hash,
    insurance_code_hash  = EXCLUDED.insurance_code_hash,
    gender               = EXCLUDED.gender,
    date_of_birth        = EXCLUDED.date_of_birth,
    age_group            = EXCLUDED.age_group,
    loaded_at            = CURRENT_TIMESTAMP;

-- 9.5. LOAD DIM DOCTOR
INSERT INTO dwh.dim_doctor (
    doctor_id_source, practicing_license, doctor_name,
    specialty, hospital_key, effective_from, effective_to,
    is_current, loaded_at
)
SELECT
    d.id AS doctor_id_source,
    d.practicing_license AS practicing_license,
    d.full_name AS doctor_name,
    d.specialty AS specialty,
    COALESCE(h.hospital_key, 0) AS hospital_key,
    CURRENT_TIMESTAMP AS effective_from,
    NULL AS effective_to,
    TRUE AS is_current,
    CURRENT_TIMESTAMP AS loaded_at
FROM public.doctors d
LEFT JOIN dwh.dim_hospital h
    ON h.hospital_id_source = d.hospital_id
WHERE d.deleted_at IS NULL
ON CONFLICT (doctor_id_source) WHERE is_current = TRUE AND doctor_id_source IS NOT NULL
DO UPDATE SET
    practicing_license = EXCLUDED.practicing_license,
    doctor_name        = EXCLUDED.doctor_name,
    specialty          = EXCLUDED.specialty,
    hospital_key       = EXCLUDED.hospital_key,
    loaded_at          = CURRENT_TIMESTAMP;

-- 9.6. LOAD FACT ENCOUNTER
INSERT INTO dwh.fact_encounter (
    encounter_id_source, visit_date_key, patient_key, hospital_key,
    doctor_key, disease_key, encounter_count,
    has_lab_result, has_imaging_report, has_prescription,
    created_at_source, loaded_at, batch_id
)
SELECT
    e.id AS encounter_id_source,
    COALESCE(dd.date_key, 0) AS visit_date_key,
    COALESCE(dp.patient_key, 0) AS patient_key,
    COALESCE(dh.hospital_key, 0) AS hospital_key,
    COALESCE(doc.doctor_key, 0) AS doctor_key,
    COALESCE(dis.disease_key, 0) AS disease_key,
    1 AS encounter_count,
    EXISTS (
        SELECT 1 FROM public.lab_results lr
        WHERE lr.encounter_id = e.id AND lr.deleted_at IS NULL
    ) AS has_lab_result,
    EXISTS (
        SELECT 1 FROM public.imaging_reports ir
        WHERE ir.encounter_id = e.id AND ir.deleted_at IS NULL
    ) AS has_imaging_report,
    EXISTS (
        SELECT 1 FROM public.prescriptions pr
        WHERE pr.encounter_id = e.id AND pr.deleted_at IS NULL
    ) AS has_prescription,
    e.created_at AS created_at_source,
    CURRENT_TIMESTAMP AS loaded_at,
    'batch_' || TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS') AS batch_id
FROM public.encounters e
LEFT JOIN dwh.dim_date dd
    ON dd.full_date = e.visit_date::DATE
LEFT JOIN dwh.dim_patient dp
    ON dp.patient_id_source = e.patient_id AND dp.is_current = TRUE
LEFT JOIN dwh.dim_hospital dh
    ON dh.hospital_id_source = e.hospital_id
LEFT JOIN dwh.dim_doctor doc
    ON doc.doctor_id_source = e.doctor_id AND doc.is_current = TRUE
LEFT JOIN dwh.dim_disease dis
    ON dis.icd10_code = COALESCE(e.icd10_code, 'UNKNOWN')
WHERE e.deleted_at IS NULL
ON CONFLICT (encounter_id_source)
DO UPDATE SET
    visit_date_key      = EXCLUDED.visit_date_key,
    patient_key         = EXCLUDED.patient_key,
    hospital_key        = EXCLUDED.hospital_key,
    doctor_key          = EXCLUDED.doctor_key,
    disease_key         = EXCLUDED.disease_key,
    has_lab_result      = EXCLUDED.has_lab_result,
    has_imaging_report  = EXCLUDED.has_imaging_report,
    has_prescription    = EXCLUDED.has_prescription,
    loaded_at           = CURRENT_TIMESTAMP;

-- 9.7. LOAD FACT PRESCRIPTION
INSERT INTO dwh.fact_prescription (
    prescription_id_source, encounter_id_source, prescription_date_key,
    patient_key, hospital_key, doctor_key, drug_key,
    quantity, duration_days, prescription_line_count,
    loaded_at, batch_id
)
SELECT
    pr.id AS prescription_id_source,
    pr.encounter_id AS encounter_id_source,
    COALESCE(dd.date_key, 0) AS prescription_date_key,
    COALESCE(dp.patient_key, 0) AS patient_key,
    COALESCE(dh.hospital_key, 0) AS hospital_key,
    COALESCE(doc.doctor_key, 0) AS doctor_key,
    COALESCE(drug.drug_key, 0) AS drug_key,
    pr.quantity AS quantity,
    pr.duration_days AS duration_days,
    1 AS prescription_line_count,
    CURRENT_TIMESTAMP AS loaded_at,
    'batch_' || TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS') AS batch_id
FROM public.prescriptions pr
JOIN public.encounters e
    ON e.id = pr.encounter_id
LEFT JOIN dwh.dim_date dd
    ON dd.full_date = COALESCE(pr.created_at, e.visit_date)::DATE
LEFT JOIN dwh.dim_patient dp
    ON dp.patient_id_source = e.patient_id AND dp.is_current = TRUE
LEFT JOIN dwh.dim_hospital dh
    ON dh.hospital_id_source = e.hospital_id
LEFT JOIN dwh.dim_doctor doc
    ON doc.doctor_id_source = e.doctor_id AND doc.is_current = TRUE
LEFT JOIN dwh.dim_drug drug
    ON drug.drug_code = COALESCE(pr.drug_code, 'UNKNOWN')
WHERE pr.deleted_at IS NULL
  AND e.deleted_at IS NULL
ON CONFLICT (prescription_id_source)
DO UPDATE SET
    prescription_date_key = EXCLUDED.prescription_date_key,
    patient_key           = EXCLUDED.patient_key,
    hospital_key          = EXCLUDED.hospital_key,
    doctor_key            = EXCLUDED.doctor_key,
    drug_key              = EXCLUDED.drug_key,
    quantity              = EXCLUDED.quantity,
    duration_days         = EXCLUDED.duration_days,
    loaded_at             = CURRENT_TIMESTAMP;

-- 9.8. LOAD FACT APPOINTMENT
INSERT INTO dwh.fact_appointment (
    appointment_id_source, appointment_date_key, patient_key,
    hospital_key, doctor_key, appointment_status,
    appointment_count, loaded_at, batch_id
)
SELECT
    a.id AS appointment_id_source,
    COALESCE(dd.date_key, 0) AS appointment_date_key,
    COALESCE(dp.patient_key, 0) AS patient_key,
    COALESCE(dh.hospital_key, 0) AS hospital_key,
    COALESCE(doc.doctor_key, 0) AS doctor_key,
    a.status AS appointment_status,
    1 AS appointment_count,
    CURRENT_TIMESTAMP AS loaded_at,
    'batch_' || TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS') AS batch_id
FROM public.appointments a
LEFT JOIN dwh.dim_date dd
    ON dd.full_date = a.appointment_date::DATE
LEFT JOIN dwh.dim_patient dp
    ON dp.patient_id_source = a.patient_id AND dp.is_current = TRUE
LEFT JOIN dwh.dim_hospital dh
    ON dh.hospital_id_source = a.hospital_id
LEFT JOIN dwh.dim_doctor doc
    ON doc.doctor_id_source = a.doctor_id AND doc.is_current = TRUE
WHERE a.deleted_at IS NULL
ON CONFLICT (appointment_id_source)
DO UPDATE SET
    appointment_date_key = EXCLUDED.appointment_date_key,
    patient_key          = EXCLUDED.patient_key,
    hospital_key         = EXCLUDED.hospital_key,
    doctor_key           = EXCLUDED.doctor_key,
    appointment_status   = EXCLUDED.appointment_status,
    loaded_at            = CURRENT_TIMESTAMP;

-- 9.9. LOAD FACT CONSENT
INSERT INTO dwh.fact_consent (
    consent_id_source, start_date_key, end_date_key,
    patient_key, doctor_key, hospital_key, consent_status,
    consent_count, valid_duration_days, loaded_at, batch_id
)
SELECT
    c.id AS consent_id_source,
    COALESCE(d_start.date_key, 0) AS start_date_key,
    COALESCE(d_end.date_key, 0) AS end_date_key,
    COALESCE(dp.patient_key, 0) AS patient_key,
    COALESCE(doc.doctor_key, 0) AS doctor_key,
    COALESCE(dh.hospital_key, 0) AS hospital_key,
    c.status AS consent_status,
    1 AS consent_count,
    CASE
        WHEN c.start_date IS NOT NULL AND c.end_date IS NOT NULL
        THEN (c.end_date::DATE - c.start_date::DATE)
        ELSE NULL
    END AS valid_duration_days,
    CURRENT_TIMESTAMP AS loaded_at,
    'batch_' || TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS') AS batch_id
FROM public.consents c
LEFT JOIN dwh.dim_date d_start
    ON d_start.full_date = c.start_date::DATE
LEFT JOIN dwh.dim_date d_end
    ON d_end.full_date = c.end_date::DATE
LEFT JOIN dwh.dim_patient dp
    ON dp.patient_id_source = c.patient_id AND dp.is_current = TRUE
LEFT JOIN dwh.dim_doctor doc
    ON doc.doctor_id_source = c.doctor_id AND doc.is_current = TRUE
LEFT JOIN dwh.dim_hospital dh
    ON dh.hospital_id_source = c.hospital_id
WHERE c.deleted_at IS NULL
ON CONFLICT (consent_id_source)
DO UPDATE SET
    start_date_key       = EXCLUDED.start_date_key,
    end_date_key         = EXCLUDED.end_date_key,
    patient_key          = EXCLUDED.patient_key,
    doctor_key           = EXCLUDED.doctor_key,
    hospital_key         = EXCLUDED.hospital_key,
    consent_status       = EXCLUDED.consent_status,
    valid_duration_days  = EXCLUDED.valid_duration_days,
    loaded_at            = CURRENT_TIMESTAMP;

-- 9.10. LOAD FACT PATIENT MAPPING
INSERT INTO dwh.fact_patient_mapping (
    patient_key, hospital_key, local_patient_id,
    mapping_date_key, mapping_count, source_system, loaded_at, batch_id
)
SELECT
    COALESCE(dp.patient_key, 0) AS patient_key,
    COALESCE(dh.hospital_key, 0) AS hospital_key,
    m.local_patient_id AS local_patient_id,
    COALESCE(dd.date_key, 0) AS mapping_date_key,
    1 AS mapping_count,
    'HIS' AS source_system,
    CURRENT_TIMESTAMP AS loaded_at,
    'batch_' || TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDDHH24MISS') AS batch_id
FROM public.hospital_patient_mapping m
LEFT JOIN dwh.dim_patient dp
    ON dp.patient_id_source = m.patient_id AND dp.is_current = TRUE
LEFT JOIN dwh.dim_hospital dh
    ON dh.hospital_id_source = m.hospital_id
LEFT JOIN dwh.dim_date dd
    ON dd.full_date = m.created_at::DATE
WHERE m.local_patient_id IS NOT NULL
ON CONFLICT (hospital_key, local_patient_id)
DO UPDATE SET
    patient_key      = EXCLUDED.patient_key,
    mapping_date_key = EXCLUDED.mapping_date_key,
    loaded_at        = CURRENT_TIMESTAMP;
*/

-- ============================================================
-- 10. SAMPLE ANALYTIC QUERIES
-- ============================================================

-- Top 10 bệnh xuất hiện nhiều nhất
-- SELECT * FROM mart.vw_top_disease
-- ORDER BY total_encounters DESC
-- LIMIT 10;

-- Tổng lượt khám theo bệnh viện trong từng tháng
-- SELECT * FROM mart.vw_encounter_by_month_hospital
-- ORDER BY year_number, month_number, total_encounters DESC;

-- Top thuốc được kê nhiều nhất
-- SELECT drug_name, SUM(total_quantity) AS total_quantity
-- FROM mart.vw_prescription_by_month_drug
-- GROUP BY drug_name
-- ORDER BY total_quantity DESC
-- LIMIT 10;

-- Tỷ lệ lịch hẹn bị hủy theo bệnh viện
-- SELECT
--     hospital_name,
--     SUM(CASE WHEN appointment_status = 'CANCELLED' THEN total_appointments ELSE 0 END)::NUMERIC(18,4)
--     / NULLIF(SUM(total_appointments), 0) AS cancel_rate
-- FROM mart.vw_appointment_status
-- GROUP BY hospital_name
-- ORDER BY cancel_rate DESC;

-- Tỷ lệ consent ACTIVE/REVOKED/EXPIRED
-- SELECT * FROM mart.vw_consent_status
-- ORDER BY hospital_name, consent_status;
